### ISSUE TITLE
Add website screenshots to the events page to pretty it up

### ISSUE THREAD

**Issue by zach2825** [hackgvl/hackgreenville-com#100]
On events:pull create a laravel job or events and listeners that will navigate to the URL and generate a screenshot that will be displayed on the [orgs](https://hackgreenville.com/orgs) page

This laravel package will generate a screenshot from the URL.
https://github.com/spatie/browsershot

Events and listeners documentation
https://laravel.com/docs/8.x/events

**Comment by bogdankharchenko** [comment]
I think we do not need this for now.
