### ISSUE TITLE
Same Events showing Cancelled and Not Cancelled in the Calendar and Event Views

### ISSUE THREAD

**Issue by allella** [hackgvl/hackgreenville-com#109]
@zach2825  Looks like this could be another caching or issue from importing the events reported by @pamelawoodbrowne 

[Calendar View](https://hackgreenville.com/calendar) and [Event View](https://hackgreenville.com/events)

The [API data seems to be good](https://events.openupstate.org/api/gtc).

Code For Greenville on Nov 2nd is a good example, but there appear to be others like Women Who Code.

**Comment by allella** [comment]
@zach2825 the duplicate events issue here seems to be persistant even if running various _php artisan_ clear and cache 
 and pull commands. 

I did notice some of the older, duplicate events have a different event description value and they also don't have a URL for the offsite page.

Here's a side by side example of the Code For Greenville instance

![image](https://user-images.githubusercontent.com/1777776/140085532-25116ca7-0cfa-4b97-9b5d-11546540ef30.png)

**Comment by allella** [comment]
We had a previous duplication https://github.com/codeforgreenville/hackgreenville-com/issues/99 issue and I think we added UUIDs to get around that, so it may be worth checking if the duplicates somehow have different UUIDs.

The [app.py](https://github.com/codeforgreenville/upstate_tech_cal_service/blob/master/app.py) defines _unique_id_ values for Meetup and Eventbrite and those become the uuid values in [the events API](https://events.openupstate.org/api/gtc?tags=1).

**Comment by allella** [comment]
Documenting a workaround.

I manually cleared the _events_ table and then ran
`php artisan -f pull:events`
and the cancelled events didn't reappear.

This isn't really a fix because something was causing duplicate events, but it at least makes the HG appear to match the API data.

None of the artisan cache or event clear commands did anything to the duplicates.

It may be the case some of these events were created many months ago, before we the last pull request that dealt with duplicates.

The staging copy shows the duplication issue since I didn't truncate its _events_ table.
https://stage.hackgreenville.com/calendar

**Comment by allella** [comment]
I also noted on the stage database
`SELECT * FROM `events` WHERE `group_name` LIKE '%Code for%' AND `cache` LIKE '%cancel%'` that there are no duplicate records for the November and December Code For Greenville events which showed a fake cancelled event.

There are some older cancelled events from earlier this year, and a Brigade event that was also cancelled on Nov 7th, so the database itself doesn't seem to have records that match what we were seeing on the calendar. This suggests the problem is somewhere in the caching the application is doing with the records since the API and the _events_ table don't have records that would have caused the duplicate / cancelled records.

Using Code For Greenville in November as an example, here's a screenshot of the duplicate "cancelled" event, which wasn't actually cancelled, and the active event that actually took place that day.

![image](https://user-images.githubusercontent.com/1777776/142299737-6452b528-6b48-44f8-bebb-435ea106441f.png)

after running the workaround above the Nov 2nd red / cancelled event went away, but there was no evidence I found that the events table had a duplicate row, so it's a mystery why clearing that table fixed the issue unless it also somehow caused a cache problem to clear out.

![image](https://user-images.githubusercontent.com/1777776/142299795-f223b51b-33f7-47dd-b39d-93e56b85386a.png)

**Comment by allella** [comment]
I purged the events in working on #113, but I still think there's something goofy with the cancelled events.

It should be easier to spot them if/when the issue resurfaces since we don't have so much event crud in the database.

**Comment by zach2825** [comment]
Wow, nice job; I like the clean-up and cleaner UI on the events page. :fireworks:

**Comment by allella** [comment]
@oliviasculley 

This is not new and I never put in the time to contact the organizers while it was happening to figure out why it happened.

The Laravel app behind HG is caching results and that's likely part of the issue because if I purge the database and reimport it removes those cancelled. Though, I try not to do a purge because it removes everything, even past events, so the calendar only goes back like 15 days in the past after a purge. 

We've fixed some previous duplicates on the Larvel cache with GUIDs and keys, but there is probably still a bug that shows up on edge cases like the Greer Programmers group.

![image](https://github.com/hackgvl/hackgreenville-com/assets/1777776/e21910d4-3cef-4077-8911-257b98c72218)

It's possible it's related to something being changed or deleted on Meetup, and not cancelled, but I've never put my full effort into figure it out because some of them were explained by other issues, like below.

There are a lot less in recent months, which supports that some of the issue was from actual cancellations.

All future Code For Greenville events are cancelled, which is accurate, but all future Greer Programming Group also have a cancelled event.

I purge the HG database probably within the last two months, so whatever is triggering those Greer issues is still a mystery. I think we should try to contact Ryan Scott to ask if there were any bulk changes made to Meetup, or some other process they do regularly that might be triggering a new Meetup.com URL and causing the duplicate.

I started debugging this at one point during the pandemic and there were a lot of legit cancelled events, so it became a moving target and I paused.

One thing I recall is that a couple Eventbrite folks were incorrectly creating each individual event under a new series_id, which I don't think it how those are intended. For example, the What's Brewing events showing under different series, which I think you don't typically do in the context of a Meetup, so that looks like some user generated goofiness when it happens.

https://www.eventbrite.com/o/whats-brewing-greenville-39719311463

`{
    "pagination": {
        "object_count": 2,
        "page_number": 1,
        "page_size": 50,
        "page_count": 1,
        "has_more_items": false
    },
    "events": [
        {
            "name": {
                "text": "What's Brewing Greenville?",
                "html": "What&#39;s Brewing Greenville?"
            },
            "description": {
                "text": "Two presenters take six minutes each to describe their business & frame their questions.  Then the community helps to answer the questions.",
                "html": "Two presenters take six minutes each to describe their business &amp; frame their questions.  Then the community helps to answer the questions."
            },
            "url": "https://www.eventbrite.com/e/whats-brewing-greenville-tickets-332956440677",
            "start": {
                "timezone": "America/New_York",
                "local": "2022-09-21T08:30:00",
                "utc": "2022-09-21T12:30:00Z"
            },
            "end": {
                "timezone": "America/New_York",
                "local": "2022-09-21T09:30:00",
                "utc": "2022-09-21T13:30:00Z"
            },
            "organization_id": "758812211143",
            "created": "2022-05-03T15:49:57Z",
            "changed": "2022-09-22T02:07:12Z",
            "published": "2022-05-18T13:30:09Z",
            "capacity": null,
            "capacity_is_custom": null,
            "status": "completed",
            "currency": "USD",
            "listed": true,
            "shareable": true,
            "online_event": false,
            "tx_time_limit": 1200,
            "hide_start_date": false,
            "hide_end_date": false,
            "locale": "en_US",
            "is_locked": false,
            "privacy_setting": "unlocked",
            "is_series": true,
            "is_series_parent": false,
            "inventory_type": "limited",
            "is_reserved_seating": false,
            "show_pick_a_seat": false,
            "show_seatmap_thumbnail": false,
            "show_colors_in_seatmap_thumbnail": false,
            "source": "coyote",
            "is_free": true,
            "version": null,
            "summary": "Two presenters take six minutes each to describe their business & frame their questions.  Then the community helps to answer the questions.",
            "facebook_event_id": null,
            "logo_id": "277730289",
            "organizer_id": "39719311463",
            "venue_id": "95433169",
            "category_id": "101",
            "subcategory_id": "1001",
            "format_id": "10",
            "id": "332956440677",
            "resource_uri": "https://www.eventbriteapi.com/v3/events/332956440677/",
            "is_externally_ticketed": false,
            "series_id": "332955568067",
            "logo": {
                "crop_mask": {
                    "top_left": {
                        "x": 0,
                        "y": 0
                    },
                    "width": 800,
                    "height": 400
                },
                "original": {
                    "url": "https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F277730289%2F758810156863%2F1%2Foriginal.20220503-155043?auto=format%2Ccompress&q=75&sharp=10&s=26bd9a6e2c4741c1ffb8dd121ddc8048",
                    "width": 800,
                    "height": 400
                },
                "id": "277730289",
                "url": "https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F277730289%2F758810156863%2F1%2Foriginal.20220503-155043?h=200&w=450&auto=format%2Ccompress&q=75&sharp=10&rect=0%2C0%2C800%2C400&s=8c30a7a5028332d73a46e32b7a76dc90",
                "aspect_ratio": "2",
                "edge_color": "#a3a696",
                "edge_color_set": true
            }
        },
        {
            "name": {
                "text": "What's Brewing Greenville?",
                "html": "What&#39;s Brewing Greenville?"
            },
            "description": {
                "text": "Two presenters take six minutes each to describe their business & frame their questions.  Then the community helps to answer the questions.",
                "html": "Two presenters take six minutes each to describe their business &amp; frame their questions.  Then the community helps to answer the questions."
            },
            "url": "https://www.eventbrite.com/e/whats-brewing-greenville-tickets-366866376207",
            "start": {
                "timezone": "America/New_York",
                "local": "2022-09-21T08:30:00",
                "utc": "2022-09-21T12:30:00Z"
            },
            "end": {
                "timezone": "America/New_York",
                "local": "2022-09-21T09:30:00",
                "utc": "2022-09-21T13:30:00Z"
            },
            "organization_id": "758812211143",
            "created": "2022-06-14T15:19:20Z",
            "changed": "2022-09-22T01:37:12Z",
            "published": "2022-06-14T15:21:09Z",
            "capacity": null,
            "capacity_is_custom": null,
            "status": "completed",
            "currency": "USD",
            "listed": true,
            "shareable": true,
            "online_event": false,
            "tx_time_limit": 1200,
            "hide_start_date": false,
            "hide_end_date": false,
            "locale": "en_US",
            "is_locked": false,
            "privacy_setting": "unlocked",
            "is_series": true,
            "is_series_parent": false,
            "inventory_type": "limited",
            "is_reserved_seating": false,
            "show_pick_a_seat": false,
            "show_seatmap_thumbnail": false,
            "show_colors_in_seatmap_thumbnail": false,
            "source": "coyote",
            "is_free": true,
            "version": null,
            "summary": "Two presenters take six minutes each to describe their business & frame their questions.  Then the community helps to answer the questions.",
            "facebook_event_id": null,
            "logo_id": "302719239",
            "organizer_id": "39719311463",
            "venue_id": "101585479",
            "category_id": "101",
            "subcategory_id": "1001",
            "format_id": "10",
            "id": "366866376207",
            "resource_uri": "https://www.eventbriteapi.com/v3/events/366866376207/",
            "is_externally_ticketed": false,
            "series_id": "366821602287",
            "logo": {
                "crop_mask": {
                    "top_left": {
                        "x": 0,
                        "y": 0
                    },
                    "width": 800,
                    "height": 400
                },
                "original": {
                    "url": "https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F302719239%2F758810156863%2F1%2Foriginal.20220503-155043?auto=format%2Ccompress&q=75&sharp=10&s=b48656d64d126902f5084a4efeb603ea",
                    "width": 800,
                    "height": 400
                },
                "id": "302719239",
                "url": "https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F302719239%2F758810156863%2F1%2Foriginal.20220503-155043?h=200&w=450&auto=format%2Ccompress&q=75&sharp=10&rect=0%2C0%2C800%2C400&s=3aa0422265222f20ff6aacd6831b66ca",
                "aspect_ratio": "2",
                "edge_color": "#a3a696",
                "edge_color_set": true
            }
        }
    ]
}`

**Comment by zach2825** [comment]
@allella I'm working to remove the command that pulls events and orgs. It probably should just make the api call on page load. 

The challenge back then was the api did not retain cancelled events. If it does that now there are no problems in making that change. 

So, does the api return canceled events too so I can display them on the calendar?

**Comment by allella** [comment]
Meetup does continue to serve cancelled events in their API if we ask for it, like in [this API call](https://api.meetup.com/upstate-elixir/events?&sign=true&photo-host=public&status=upcoming,**cancelled**,past&page=50).

We are normalizing 'cancelled vs canceled' status names in the Event API, and I don't see where we are discarding cancelled events. Though, @ramonaspence may have a better answer.

I think the reason the Events API doesn't show any future cancelled events is they were all actually deleted on Meetup.

I can't speak for what happened with the Greer Programmers' Group, but it appears they deleted events because the [HG events page](https://hackgreenville.com/events) has two different URLs for the Greer Programmers Group "Programmers & Tech Gathering" and one of those URLs is now a 404. I don't think the Events API is generating those Meetup URLs, so it would seem that both 

- Missing - probably deleted https://www.meetup.com/greer-programmers-group/events/mjprwsyfcjbdc/
- Active - https://www.meetup.com/greer-programmers-group/events/qltjftyfcjbdc/
- 

The Code For Greenville events that are showing as cancelled were deleted on Meetup.com, so that's part of what's showing as red on the HG site. In the case of CFG, I deleted the future events because that Meetup group is rebranding and merging into _Code For The Carolinas_' Meetup account, due to Code For America forcing things on the local brigades. 

I suppose if an organizer deletes an event that we shouldn't continue to list it because it's more likely they would delete something for being a duplicate, or else because they don't want a record of the event even being created.

**Comment by allella** [comment]
The other thing with the Events API is we only serve up to so many days in the past, which is currently set to 30.

So, the events and calendars would be empty if we go back more than 30 days, which I don't see as a big issue.

Eventually we should get a real database behind the Events API so we have the option to store older events and let folks query the API for older stuff if they have a use case.  Though, most of the use cases we have now are interested in recent and upcoming events and not stuff from months ago.

**Comment by zach2825** [comment]
Thank you, I plan on working on this next. I wanted to get updates, UI improvements, and cleanup done before tracking this since it is a big piece of code.

**Comment by allella** [comment]
Closed by #154
