### ISSUE TITLE
mobile hamburger menu not opening when clicking

### ISSUE THREAD

**Issue by zach2825** [hackgvl/hackgreenville-com#118]
![image](https://user-images.githubusercontent.com/4049321/185495782-b207dd48-3221-40b4-afdb-e793d41057be.png)

**Comment by bogdankharchenko** [comment]
This works on my phone - can we get more info of the browser/screen size?

**Comment by zach2825** [comment]
Just when I pull down the latest changes in dev and shrink the latest chrome browser to a size that shows the mobile nav the hamburger menu stopped working. 
Not the hackgreenville.com site yet but the latest dev

**Comment by bogdankharchenko** [comment]
Can't replicate this locally.

**Comment by allella** [comment]
Also can't replicate in latest Chrome or Firefox.

@zach2825 can you try on https://stage.hackgreenville.com

**Comment by allella** [comment]
Good first issue to see if anybody else can recreate Zach's report.

**Comment by zach2825** [comment]
Working now, this can be closed.
