### ISSUE TITLE
Improve on UI and styleguide 

### ISSUE THREAD

**Issue by zach2825** [hackgvl/hackgreenville-com#136]
I rushed through when I first did the work to update the site. I want to take a little longer and improve the UI and utilize the space better

**Comment by zach2825** [comment]
Home page updates:
![image](https://github.com/hackgvl/hackgreenville-com/assets/4049321/6af2efd4-be48-4919-aee7-09e3c91be51e)

About US page updates
![image](https://github.com/hackgvl/hackgreenville-com/assets/4049321/3e431a16-5d9a-4441-926a-f3fac5a8c284)

**Comment by zach2825** [comment]
I added a container around the homepage content, spaced things a little better in the footer and on the about us page I added some styling and elements to space things are a little better.

**Comment by allella** [comment]
Two smaller notes.

We're mostly using HackGreenville as one word with both H and G capitalized.  There's some inconsistency on the homepage we could iron out while we're at it.

Code For Greenville is rebranding and ending at the end of this month.  We can rename "Code For Greenville" to "HackGreenville Labs" on the About page. Though, we should leave a note in there like '...nutured and expanded by the former Code For Greenville brigade. The site and underlying open data APIs are now supported by HackGreenville Labs to promote...

Also, we're planning to add a "Labs" page to the site, which will mostly highlight the HG supported projects as noted on this CFG site that's no longer active. https://hackgvl.github.io/codeforgreenville.github.io/

**Comment by zach2825** [comment]
I made the changes and pushed them up, thanks @allella!
