### ISSUE TITLE
Give credit to Karla and Zach Robichaud for the logo and styles on the /styles page

### ISSUE THREAD

**Issue by allella** [hackgvl/hackgreenville-com#140]
Had this on my to-do list.

We have Zach on the README via the All Contributors, but wanted to give credit where it's due for the logo, styles and such on that 
https://hackgreenville.com/styles page.

and, add Karla to the README if she's on GitHub.

**Comment by zach2825** [comment]
She's not on github but she has a website I can add the stuff, thank you.
