### ISSUE TITLE
Execution depedency in composer install prior to running Docker containers

### ISSUE THREAD

**Issue by irby** [hackgvl/hackgreenville-com#158]
Inside `composer.json`, one of the `post-install-cmd` commands is to perform a database migration. This becomes problematic when trying to run the Docker containers for the first time. The `docker-compose.yml` requires `hackgreenville` to be built off the Dockerfile inside `vendor`, which turns into a chicken-and-egg problem.

So, if you're trying to get the Docker containers running for the first time, you'd need to run `composer install`, but this script will fail because you don't have a database yet available to run migrations against (unless you're running MySQL on bare metal).

My suggestion is to have a Dockerfile pre-defined so you don't need to run `composer install` to build out your Docker images, or remove `php artisan migrate --seed` from the `composer.json` post-install commands.

**Comment by bogdankharchenko** [comment]
@irby I second removing `php artisan migrate --seed` from composer json.

Go ahead and pull a PR

**Comment by irby** [comment]
@bogdankharchenko PR up!

**Comment by bogdankharchenko** [comment]
I can't officially review PR's here, but @allella this looks good to me.
