### ISSUE TITLE
Doc: `sh scripts/handle-deploy-update.sh` does not exist

### ISSUE THREAD

**Issue by alexdresko** [hackgvl/hackgreenville-com#173]
In https://github.com/hackgvl/hackgreenville-com/blob/develop/CONTRIBUTING.md#installing-dependencies-and-seeding-database, it is instructed to run `sh scripts/handle-deploy-update.sh`. However, that file does not exist in the repo. 

I don't know if the repo is wrong or if the doc is wrong. I'm trying to follow CONTRIBUTING.md to get started, but I ran into this problem. 

I'm kind of a n00b with this stuff... Hence the reason I'm trying to build a dev container to make it easier for people.

**Comment by alexdresko** [comment]
Ignore me. I just needed to pull from upstream.

**Comment by allella** [comment]
Yeah, Zach and Bogdan made a lot of changes, so that pull should have been a big one.

**Comment by allella** [comment]
I guess this will be confusing for people who already have a fork since that script does the git pull and the script won't existing unless you have git pull'ed already.

There aren't too many other folk who should fall into that category, but it's good to keep in mind.
