### ISSUE TITLE
"Package laravelcollective/html is abandoned, you should avoid using it. Use spatie/laravel-html instead."

### ISSUE THREAD

**Issue by ThorntonMatthewD** [hackgvl/hackgreenville-com#180]
The [laravelcollective/html](https://github.com/LaravelCollective/html) package is no longer being maintained, and [spatie/laravel-html](https://github.com/spatie/laravel-html) is its recommended replacement.

**Comment by bogdankharchenko** [comment]
Should we just kill this package all together and use raw html?

Also, I have been using this package for many years now - on a daily basis, [https://airephp.com/](https://github.com/glhd/aire) - it is great in every aspect - it also has a bootstrap option.

**Comment by allella** [comment]
@zach2825 what say you?
