### ISSUE TITLE
Dev Documentation tweaks

### ISSUE THREAD

**Issue by JSn1nj4** [hackgvl/hackgreenville-com#206]
I was setting up the project fresh over the weekend and had a tweak I'd like to make to CONTRIBUTING.md.

## CONTRIBUTING.md edits
In Setup & Configuration... > Option 1 > ["Import / Seed the Organizations and Events Data"][opt1_import], the commands didn't work. It sounds like the commands might've been replaced:
```shell
# old
php artisan pull:orgs
php artisan pull:events

# new
php artisan import:events
```

If it's alright, I'd like to throw a PR together for this minor change while I work out a PR for a different issue.

[opt1_import]: https://github.com/hackgvl/hackgreenville-com/blob/develop/CONTRIBUTING.md#import--seed-the-organizations-and-events-data

**Comment by allella** [comment]
Yes, I had that on my to-do list to update since last week when we deployed a major API change from Bogdan.

  The _import:events_ is the new command, so please feel free to update that section.

**Comment by allella** [comment]
We also no longer use the API endpoint as described at https://github.com/hackgvl/hackgreenville-com?tab=readme-ov-file#apis since the API is now in the Laravel stack.

There's other changes, so I can take care of updating those docs, but please do send a PR for the Artisan changes and feel free to ask about other things that don't line up because the APi changes didn't include docs changs.

**Comment by JSn1nj4** [comment]
Ah ok, I was going to ask something related to seeding earlier, but I think that answers that. I'll dig into the OpenData project for seeding.

**Comment by bogdankharchenko** [comment]
> Bogdan was talking about moving the organizations moved into the Laravel site and said we didn't need to import organizations now.
> 
> @bogdankharchenko are we still pulling orgs from https://data.openupstate.org/organizations ?

No we will not longer need to pull orgs, we will instead install `filamentphp` to manage organizations in this repo.

**Comment by bogdankharchenko** [comment]
> I was setting up the project fresh over the weekend and had a tweak I'd like to make to CONTRIBUTING.md.
> 
> ## CONTRIBUTING.md edits
> In Setup & Configuration... > Option 1 > ["Import / Seed the Organizations and Events Data"](https://github.com/hackgvl/hackgreenville-com/blob/develop/CONTRIBUTING.md#import--seed-the-organizations-and-events-data), the commands didn't work. It sounds like the commands might've been replaced:
> 
> ```shell
> # old
> php artisan pull:orgs
> php artisan pull:events
> 
> # new
> php artisan import:events
> ```
> 
> If it's alright, I'd like to throw a PR together for this minor change while I work out a PR for a different issue.

We will need to setup a seeder/prod data dumps for Organizations.   I will try to get to this today but feel free to take a stab at this!
