### ISSUE TITLE
Greenville Library System Events - Custom API

### ISSUE THREAD

**Issue by allella** [hackgvl/hackgreenville-com#222]
@ChristinaDRoberts mentioned seeing a library computer class posted.

The [Greenville County Library System has a number of adult and kids classes / events](https://www.greenvillelibrary.org/events), which we've never syndicated because there probably was no structured data or API.

However, there is now a custom API that's public and easy to figure out using web dev tools in the browser. 

"Computer Classes" (event-type=12)
https://www.greenvillelibrary.org/api/v2/events?mode=calendar&group=1&date-start=2024-01-28&date-end=2024-03-02

"Computer Classes" (event-type=12) and "STEAM" (event-type=19)
https://www.greenvillelibrary.org/api/v2/events?event-type=**12+19**&mode=calendar&group=1&date-start=2024-01-28&date-end=2024-03-02

There are other filters, like "Location", which the API can filter.

They have a decent number of events and aren't historically the "HackGreenville" crowd, since it's more of a tech beginner (kids or adults), but we do have enough overlap into listing [other STEAM and career changers orgs](https://hackgreenville.com/orgs) that it's probably worth consideration now that it looks like there's some custom structured data from their Drupal API.

**Comment by ThorntonMatthewD** [comment]
[greenville-library-openapi-spec.json](https://github.com/hackgvl/hackgreenville-com/files/14131780/greenville-library-openapi-spec.json)

OpenAPI spec for the `/api/v2/events` endpoint, along with a couple of others.

**Comment by allella** [comment]
Tagging with "suggestion" and putting on the list of future ideas to clean up the active issue queue.
https://github.com/orgs/hackgvl/projects/7
