### ISSUE TITLE
Add RefactorGVL Links to the Footer and About Page

### ISSUE THREAD

**Issue by allella** [hackgvl/hackgreenville-com#224]
Now that HG is an initiative of https://refactorgvl.com/ we could add something like

_HackGreenville is a program of the [RefactorGVL](https://refactorgvl.com/)_ non-profit.

to the footer and somewhere in the [About page](https://hackgreenville.com/about) / history.

**Comment by allella** [comment]
I suppose we could add the RefactorGVL logo to the about page too.

**Comment by JSn1nj4** [comment]
@allella I figured I'd start this just to knock it out. On the About page, do you think something should be written about it in this area, before the last paragraph?
![image](https://github.com/hackgvl/hackgreenville-com/assets/5084820/aed196bc-236b-400f-84a0-8ae29751afbe)

**Comment by allella** [comment]
@JSn1nj4 Yes, I would say we could add something like

> In Nov. 2023, HackGreenville establish a collaborative relationship with [RefactorGVL](https://refactorgvl.com), a local 501(c)(3) non-profit, to further their mission of elevating the tech community in the Upstate. This collaboration provides infrastructure, fiscal sponsorship, and other support services to HackGreenville as it serves the local workforce.

**Comment by JSn1nj4** [comment]
If HackGreenville is a program of RefactorGVL now, does that mean the copyright should be RefactorGVL's?

**Comment by allella** [comment]
I see I put "establish" instead of "established" in the RefactorGVL text.  If you want to push that fix, then I think we're good to go.

Thanks again for leading the charge.
