### ISSUE TITLE
Bug: Import Events Yields 'Undefined array key "state"' Exception on Event with no State Set 

### ISSUE THREAD

**Issue by allella** [hackgvl/hackgreenville-com#225]
I actually tried to run the importer by hand using `php artisan import:events`, to test a workaround for https://github.com/hackgvl/hackgreenville-com/issues/213, on production and it processed some orgs and events, up through _Greenville SC WordPress Meetup Group_ and then seems to fail on _Greenville Three.js Meetup Group_

The [~~first record in the~~ Meetup.com REST API for _Greenville Three.js Meetup Group_](https://api.meetup.com/greenville-webgl-meetup-group/events?&sign=true&photo-host=public) has no "State" value set in the venue.  ~~The other records do have a state set~~, but this is obviously causing an error on the importer.

![image](https://github.com/hackgvl/hackgreenville-com/assets/1777776/8b424157-5e3e-490e-a89e-899aba386a1a)

![image](https://github.com/hackgvl/hackgreenville-com/assets/1777776/e043982a-0cf9-4e8c-a225-87c7332c08ea)

**Comment by allella** [comment]
Actually, I see all of the venue records for Greenville Three.js Meetup Group in the Meetup REST API are missing a state.

I'll connect with Nate to update that as a work around, but it seems will need to catch errors for missing values like this on the Laravel side.

**Comment by allella** [comment]
@bogdankharchenko thanks for #226 

It got the importer working again, but I'm curious if [Three.js events](https://api.meetup.com/greenville-webgl-meetup-group/events?&sign=true&photo-host=public) will continue to have an import issue if that missing state / zip remained.

Nate and I are talking in the Slack about it, and it may be that he's using the mobile app and it doesn't ask for a state, just a zip code.

![nate-three-js-meetupbug](https://github.com/hackgvl/hackgreenville-com/assets/1777776/3fd41b40-0dc8-455f-82bb-635a2b77b085)

**Comment by allella** [comment]
The fix on the Meetup.com / data side from Nate / Three.js was "I changed it on the desktop site. Before, I searched and selected the location but this time I manually copy pasted the full address"

This corrected the missing State and Zip Code in the _Venue_ in [Meetup REST API](https://api.meetup.com/greenville-webgl-meetup-group/events?&sign=true&photo-host=public) 

![image](https://github.com/hackgvl/hackgreenville-com/assets/1777776/db747d8f-261d-4802-bcf4-e3f30559eb76)

**Comment by allella** [comment]
This issue is also happening with at least one Synergy Mill event that just passed on Feb 4, 2024

![image](https://github.com/hackgvl/hackgreenville-com/assets/1777776/0520772d-11de-43bb-a1af-895f973ad2f9)

**Comment by allella** [comment]
@jhloman the _Bass Day V_ event from Feb 4 was missing a state and zip code on the "venue".

Nate, one of the other organizers, [was able to fix the issue by updating the venue on the event](https://github.com/hackgvl/hackgreenville-com/issues/225#issuecomment-1941588232).  Would you mind giving that a try and takes some screenshots of the process?

We are catching and logging this error in the app, but I suspect it will continue to happen from time to time and it would help to document the steps organizers can take to fix it so we can fix the problem in the data, instead of hacking around the bad data.

**Comment by allella** [comment]
@bogdankharchenko in another wrinkle on this issue, we are seeing duplicates in the events API for Three.js as seen in the [calendar](https://hackgreenville.com/calendar) and #events channel digest.

Nate did edit the venue to add a zip code and state and perhaps that triggered new records on the import from the venue change?

The Meetup API looks to not have duplicates, so it doesn't seem that causing any direct issue with duplicates
https://api.meetup.com/greenville-webgl-meetup-group/events?&sign=true&photo-host=public

**Comment by allella** [comment]
It sounds like a change to recurring events is the most likely cause, since this didn't seem to happen immediately after the venue change, and since Nate is saying he switched to recurring

![image](https://github.com/hackgvl/hackgreenville-com/assets/1777776/aca06150-ae69-4fd4-a927-4a0cf777bd63)

**Comment by zach2825** [comment]
Hey guys, 

The relavent lines related to this issue, the fix is good because it'll prevent it from bombimg out. But, It could be handled with an Arr::get accessor or using PHPs `?? ''` fallback syntax

So the lines are currently 
```php
         return VenueData::from([
                'id' => $data['venue']['id'],
                'name' => $data['venue']['name'],
                'address' => $data['venue']['address_1'] ?? '',
                'city' => $data['venue']['city'],
                'state' => $data['venue']['state'],
                'zip' => $data['venue']['zip'],
                'country' => $data['venue']['country'],
                'lat' => $data['venue']['lat'],
                'lon' => $data['venue']['lon'],
            ]);
```

they could be 
```php
         return VenueData::from([
                'id' => $data['venue']['id'],
                'name' => $data['venue']['name'],
                'address' => $data['venue']['address_1'] ?? '',
                'city' => $data['venue']['city'] ?? '',
                'state' => $data['venue']['state'] ?? '',
                'zip' => $data['venue']['zip'] ?? '',
                'country' => $data['venue']['country'] ?? '',
                'lat' => $data['venue']['lat'] ?? '',
                'lon' => $data['venue']['lon'] ?? '',
            ]);
```

So, we'd catch all the optional params like state, zip, and country for example and default them to empty string or null to prevent the undefined errors from popping up. 

Take note in this same test code
![image](https://github.com/hackgvl/hackgreenville-com/assets/4049321/1e1e0176-cf9a-4f24-b78e-a69fd5fdcfc3)


See after adding `?? ''` The test passes now. I also added an equals check, you can see that it defaults to n/a now
![image](https://github.com/hackgvl/hackgreenville-com/assets/4049321/3b9e820c-bd2a-4256-b6bf-0c40f441363a)

**Comment by allella** [comment]
Thanks @zach2825 this would certainly help avoid the the bloat in the error logs.  If allowing the missing data isn't going to cause any issues downstream, then defaulting to empty strings may do the trick.

The only app I can think using the city, state, zip so far is the Slackbot.  So, if we did empty strings we'd probably actually get an easy way to catch future events with missing values.  Though, perhaps in the long run we'd want to figure a more proactive way to identify bad upstream events.  @oliviasculley is a missing city, state, or zip in the Events API, due to missing data from Meetup or Eventbrite, going to mess up the Slackbot if we're more permissive about allowing events even if these values are not complete?

@bogdankharchenko are there any foreseen reasons why passing empty strings in a venue is going to cause trouble either in the app itself, or in API consuming applications?

I briefly started to mess around with a custom catch to log the offending organization and meetup event.  That could be a new feature, instead of expanding this bug fix, but it may be helpful to know when events are giving us missing values so we can give the organizers a heads up to investigate / fix things upstream.  So, we could do something like check if any of the values are unexpectedly empty on import and log a minimal set if info in the logs so we can have another way to be proactive with giving organizers a heads up to fix their event info.

**Comment by allella** [comment]
@bogdankharchenko Zach's changes further improved avoiding this error for undefined venue values and such.  Though, I did have a question in the last comment about if setting these undefined values is going to cause any other unexpected issues with the importing.

**Comment by bogdankharchenko** [comment]
> @bogdankharchenko are there any foreseen reasons why passing empty strings in a venue is going to cause trouble either in the app itself, or in API consuming applications?

We should just return NULL when there is no venue.

**Comment by allella** [comment]
@bogdankharchenko you know better than me, so we can give that a try.

Relatd to this, I had to silence the Luma importer venue warnings about missing data.

Of course, when something is missing in these venues we get a huge dump in the Slack log, and we get it every hour on the same event.

I'm not sure what the best solution is, but something that gives us a heads up one time, perhaps with less dump and more of a custom message, and only when something has changed, might be the middle-ground on these venues.

**Comment by bogdankharchenko** [comment]
@allella https://github.com/hackgvl/hackgreenville-com/pull/378/files

We can simply change the luma logs to be a "debug" log, and only notify slack if there are "warning" level logs.

**Comment by allella** [comment]
I feel like we're going to want to tighten up the recurring hourly errors at some point, but this is a good step.

Thanks.
