### ISSUE TITLE
Set up base filament dashboard + admin commands for managing users

### ISSUE THREAD

**Issue by JSn1nj4** [hackgvl/hackgreenville-com#229]
We have 1 issue (#210) that wants Filament, and another potential use of Filament for the recently-added [give page](https://hackgreenville.com/give).

In light of that, I'd like to set up Filament standalone first + a command or 2 for adding/deleting admin accounts.

Commands could be like:
```php
artisan user:invite <email> <fname> <lname>
artisan user:deactivate <email>
artisan user:activate <email>
artisan user:delete <email>
```

**Comment by allella** [comment]
@zach2825 had a login in place years ago. I never did use it, so I'm not sure if any code or database is still around.

We may want to check that any old stuff is pruned in the process of moving to a new admin UI.

@JSn1nj4 what's the alternative to "standalone" and using Artisan commands?  I've not used it before so I'm not familiar with the options and vocabulary.

**Comment by JSn1nj4** [comment]
@allella 
Sorry, maybe poor choice of wording. I just mean instead of bundling the admin dashboard with one of the other features first.

Once the Filament dashboard is created, it'll be trivial to add at least a user index page. Other CRUDs for user management would be easy too, but I figured having the administrative commands from the server side would give the server admin a good backup for user management.

**Comment by zach2825** [comment]
I'd completely support using filament I don't remember if the thing I setup It's still in place. Filament is pretty amazing.

**Comment by JSn1nj4** [comment]
> I'd completely support using filament I don't remember if the thing I setup It's still in place. Filament is pretty amazing.

I did see an old login page, though not a dashboard...yet. I'll poke around though just in case.

I know Laravel also has a default `HOME` URL it directs successful logins to in 1 of the built in classes, so I'll see if that needs changing.
