### ISSUE TITLE
Disable telescope by default

### ISSUE THREAD

**Issue by allella** [hackgvl/hackgreenville-com#233]
![image](https://github.com/hackgvl/hackgreenville-com/assets/1777776/bbd8a06f-2514-4775-9636-39fed5e4fad5)

> 
> I noticed some MySQL issues on the HG site in the production log related to the telescope_entries table.
> These errors appear to be happening on the artisan command on the top of every hour. It's likely because select count(*) as aggregate from `telescope_entries` is trying to operate on a telescope_entries table is over 5.1 GB of data in the database and 6.8 million rows.  So, it's probably a timeout because the database isn't tuned for this query on an increasingly large blob of data.
> I see "laravel/telescope" is under "require-dev" in Composer and am wondering if it's even supposed to be logging things on production. Or, if this is needed during the artisan event import command.
> Also,  https://github.com/hackgvl/hackgreenville-com/issues/225 is still causing a good deal of noise in the logs, since we're catching and logging the exception.  I may update the catch on that so it only logs the name and event ID of the ones that fail, instead of the all the exception noise that's currently being logged

**Comment by zach2825** [comment]
The problem is that the database tables are getting too large; if you guys check out the documentation and how powerful and valuable the Telescope is, you'll see its usefulness. 

The real fix is to add a [scheduled command](https://laravel.com/docs/10.x/telescope#data-pruning) to clean them up.

**Comment by allella** [comment]
@zach2825 is this supposed to be running in production? It's listed in _require-dev_, but it's still logging production artisan commands.  The docs say "your local Laravel development environment".

I don't know anything of Telescope. If it's a dev tool, then we can keep it around for dev or stage, but I'm not sure what we're missing out on for production.

**Comment by zach2825** [comment]
I'm looking at it, it should not install or run in production too. I'm working on it I'll have a PR soon :)

**Comment by bogdankharchenko** [comment]
> I'm looking at it, it should not install or run in production too. I'm working on it I'll have a PR soon :)

We should ensure when installing composer dependencies in prod, we use 
`composer install --no-dev`

**Comment by allella** [comment]
@bogdankharchenko That's a good call.  https://github.com/hackgvl/hackgreenville-com/blob/develop/scripts/handle-deploy-update.sh is probably the cause of it, since we don't have --no-dev on that script.

I guess part of the solution is to update that deploy script.
