### ISSUE TITLE
Bug: Blank "Organization Type" field for New Organizations Upon Creation in Filament 

### ISSUE THREAD

**Issue by allella** [hackgvl/hackgreenville-com#300]
I created the new https://hackgreenville.com/orgs/upwise group and the Focus Area and Organization Type were blank. Though, I've since manually fixed them in the database.

The [Focus Area is missing on the form and has its own issue](https://github.com/hackgvl/hackgreenville-com/issues/297).

The "Categories" field does show on the Filament UI for organizations and that field saves to an _orgs.category_id_ foreign key integer.

The value in the _orgs.organization_type_ has text that's similar to the Category and it's unclear why we need both Category and "Organization Type", so perhaps the solution is to remove "Organization Type" and display the category text on the organization detail pages.

**Comment by bogdankharchenko** [comment]
@allella I cannot replicate this issue

**Comment by allella** [comment]
Thanks. It seems like we no longer have both Categories and Organization Type fields on the edit page, so I think we're good on that.  And, #297 seemed to take care of that issue on the form.

**Comment by allella** [comment]
@bogdankharchenko I'm re-opening this early issue because we're still seeing the "Organization Type" being null when creating a new organization, as least in some situations like my test below.

I created Pixel Pushers to test on stage and it created the org, but there's no value for "Organization Type" on the org's view and there's no "Organization Type" field on the create admin page.

There is a "Category" field on the org creation, and I set that to "Meetup Groups". Though, it seems we're either missing a field on the admin, or if "Category" is the same as "Organization Type", then the value isn't being saved when an org is created via the admin form.

![image](https://github.com/user-attachments/assets/64a35b73-9ede-4492-92d5-8d77aa0085d2)

![image](https://github.com/user-attachments/assets/5b63ca92-81b9-4b51-b390-9ca33fcb3a34)

**Comment by allella** [comment]
Also, here's the database table showing the NULL organization_type when doing ``SELECT category_id, slug, organization_type from orgs;``

![image](https://github.com/user-attachments/assets/753c3320-8c71-4a8d-9364-c4fa1843f9de)

**Comment by allella** [comment]
I've manually fixed the record in the table on stage, and will do the same on live, but the screenshots above show the state of the issue before the manual fix.

``UPDATE orgs SET organization_type = "Meetup Groups" WHERE id = 73;``

**Comment by bogdankharchenko** [comment]
@allella is this still an issue? Sorry I may have missed this

**Comment by allella** [comment]
@bogdankharchenko yes, I had the issue again and posted more notes here two days ago.  The _organization_type_ in the database isn't being set when an organization is created via Filament.  There's a "Category" field in Filament that perhaps is supposed to be the organization_type, but if that's the case it's not saving.
