### ISSUE TITLE
Add Code of Conduct to Website

### ISSUE THREAD

**Issue by eric1234** [hackgvl/hackgreenville-com#313]
At the most recent committee meeting, it was agreed to move forward with the Code of Conduct and all HG committee members have approved it. I think it should be posted:

* On the website somewhere. A canonical location like http://hackgreenville.com/coc to make it easy to reference
* Reference it on the "Join Slack" page at https://hackgreenville.com/join-slack. I think it's fine to keep the existing rules as they provide a nice common sense list. But maybe just adjust the "agree" text to say "Do you accept the rules and agree to abide by our Code of Conduct?" linking the term "Code of Conduct" to the coc page.

**Comment by bogdankharchenko** [comment]
@allella should we replace the current rules on: https://hackgreenville.com/join-slack to point to Code of Conduct or should we add it as an additional line item?

**Comment by allella** [comment]
Maybe add a link "Members agree to honor the HackGreenville Code of Conduct" ?
