### ISSUE TITLE
Detatch Fork

### ISSUE THREAD

**Issue by bogdankharchenko** [hackgvl/hackgreenville-com#361]
We should detach this project form the forked sc-codes projects.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/detaching-a-fork

**Comment by allella** [comment]
We could ask Creighton to close that original repo if that's of any value.

**Comment by bogdankharchenko** [comment]
it would be nice not be to associated with the original project

**Comment by allella** [comment]
I mean, I don't think it's worth losing all of our history, issues, prs, and such just to detach. Am I missing something?

**Comment by irby** [comment]
Hmmm it does seem pretty explicit that detaching the fork will result in issues, PRs, etc being deleted. Not sure we can get around that.

**Comment by bogdankharchenko** [comment]
An answer on stackoverflow

<img width="727" alt="Screenshot 2024-08-02 at 11 23 00 AM" src="https://github.com/user-attachments/assets/21350bd8-6de5-4b4f-8d02-5818f4694f68">

**Comment by allella** [comment]
The 2021 notes don't exactly line up with the current UI, but I think we're on the right path.

The main questions is if they will approve this for an organization owned fork.  

The SO notes say "your-username" and if that doesn't include orgs, then perhaps we're SOL.

I can give it a try, but I'm not 100% on the Detach vs Extract in the chat UI.

I don't exactly know what "network" means in this context and if we need a Detach, an Extract, or both.

![image](https://github.com/user-attachments/assets/aeb6be84-8553-45c2-b215-87bc89947e69)

**Comment by bogdankharchenko** [comment]
Userrame/Network is: `hackgvl` and repo is `hackgreenville-com`

Also, I think we should convert the "feature" issues into tickets in the HG Project -- and reduce out issue count in this repo - and only reserve it for real issues not features

**Comment by allella** [comment]
@bogdankharchenko this repo has been detached from @magoun 's original
https://github.com/hackgvl/hackgreenville-com
