### ISSUE TITLE
Bug: Unpublished Events Showing in Calendar

### ISSUE THREAD

**Issue by allella** [hackgvl/hackgreenville-com#374]
@bogdankharchenko 

I did a test by unpublishing a Tech After Five's Charlotte, NC event on August 13th on the stage site.

It dropped off the Events page, but it's still on the [calendar](https://stage.hackgreenville.com/calendar)

![image](https://github.com/user-attachments/assets/e988cb0e-8ba6-4d35-9bf7-ffffa6eb2df9)

**Comment by bogdankharchenko** [comment]
I'll PR a fix for that in sec
