### ISSUE TITLE
Bug: Upcoming Events on Homepage only Showing DefCon

### ISSUE THREAD

**Issue by allella** [hackgvl/hackgreenville-com#382]
I'm assuming this could be related to the recent change of the sorting of that block.

While we're in there, it would probably be good to make the "Upcoming Events" heading into a link to the /events page

![image](https://github.com/user-attachments/assets/82f1e3b0-96ab-4d49-8832-14e2c5c35aad)

**Comment by irby** [comment]
I can take this one on -- pretty easy fix.

**Comment by irby** [comment]
@allella This should be resolved by the merge of #384 that Bogdan made earlier today.

**Comment by allella** [comment]
Thanks. It's live now.
