### ISSUE TITLE
Event property `event_type` is not persisted

### ISSUE THREAD

**Issue by irby** [hackgvl/hackgreenville-com#395]
While working on #393 I noticed the `event_type` property mapped in `EventData` is not stored anywhere in the `Event` model in the DB. Since it's not being used, I propose we get rid of this property required for the [EventData construct](https://github.com/hackgvl/hackgreenville-com/blob/develop/app-modules/event-importer/src/Data/EventData.php#L26). Otherwise, we acquire tech debt trying to maintain a mapping for a field that is never used.

**Comment by allella** [comment]
I don't recall an [event type](https://github.com/hackgvl/events-api/) in the old API, but will defer to Bogdan on what / if we're using it for in the new one.
