### ISSUE TITLE
Add ci cd scripts

### ISSUE THREAD

**Issue by zach2825** [hackgvl/hackgreenville-com#68]
I am partial to using Envoy. The script is very clean and easy to use. But we can use pure GitHub ci

https://github.com/ohdearapp/gitlab-ci-pipeline-for-laravel/blob/master/.gitlab-ci.yml

Laravel envoy is free and super easy to setup. 
https://laravel.com/docs/8.x/envoy

**Comment by jdonboch** [comment]
what type of tasks would be performed by the CICD scripts?  are there any manual steps documented somewhere that can be automated via CICD? 

I'm new but looking at the contributing page I don't see any instructions on a standard set of tasks (i.e. linting, static analysis, etc) or testing that needs to be performed and passing.  These are typically the easiest things to automate first as part of a CICD.

**Comment by allella** [comment]
It's Laravel, but I'm not sure we've been running any of these dev tasks.

The production go-live tasks are using Laravel's Artisan and I'm sure it has some of these common tasks built in, but Zach would have to answer about what's already useful and practical for the app.

For production, we run the following tasks
_git pull && composer install; php artisan test && php artisan migrate_

**Comment by allella** [comment]
@zach2825 is there a short list of specific tasks or commands we'd want to involve in the CICD process?

I'm new to this stuff, so I'm not sure where we'd start and @jdonboch offered some expertise if we provide a direction.

**Comment by allella** [comment]
Also, would we start with code related tasks or deployment related tasks?  Again, I'm new to this stuff.

We've been using a manual [gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) process that I use to merge the develop to the master branch.  

We also have a development site.  The typical process has been to merge dev to master, pull master to the stage site, have someone click around at https://stage.hackgreenville.com and then pull master on the live site when things look good.

**Comment by allella** [comment]
This is somewhat copy/paste and some off the top of my head, but here's the overall process for deploying code.

**On Github**
We usually merge pull request into develop branch.

**On stage**
```
git checkout master && git pull && git checkout develop && git pull
git flow release start {next-semantic-version here}
git flow release finish {next-semantic-version here}
git push
git checkout master && git pull && composer install; php artisan test && php artisan migrate
```
**On Live** (master branch is the only branch)
`git pull && composer install; php artisan test && php artisan migrate`

**Comment by bogdankharchenko** [comment]
@allella can we close this ticket?

**Comment by allella** [comment]
Sure, the _scripts/handle-deploy-update.sh_ does much of the deploy work.

We can eventually try to make things automatic, but it's not a high priority item right now and the RefactorGVL partnership could change some things about the hosting, so no sense in build for unknowns.
